name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: checkout project
      with:
        fetch-depth: 1

    - name: install dependecies
      run: sudo apt install libusb-dev

    - name: build
      run: make
